-- MySQL Script generated by MySQL Workbench
-- Sun Apr 19 22:13:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AgroFlightOps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AgroFlightOps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AgroFlightOps` ;
USE `AgroFlightOps` ;

-- -----------------------------------------------------
-- Table `AgroFlightOps`.`perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`perfis` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `ativo` TINYINT NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`nome` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`usuarios` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha_hash` TEXT NOT NULL,
  `perfil_id` BIGINT UNSIGNED NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`email` ASC) VISIBLE,
  INDEX `idx_usuarios_perfil_id` (`perfil_id` ASC) VISIBLE,
  INDEX `idx_usuarios_ativo` (`ativo` ASC) VISIBLE,
  INDEX `fk_usuarios_perfil_id` (`perfil_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_perfil_id`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `AgroFlightOps`.`perfis` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`clientes` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cpf_cnpj` VARCHAR(18) NULL DEFAULT NULL,
  `telefone` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `numero` VARCHAR(20) NULL DEFAULT NULL,
  `complemento` VARCHAR(120) NULL DEFAULT NULL,
  `bairro` VARCHAR(120) NULL DEFAULT NULL,
  `municipio` VARCHAR(120) NULL DEFAULT NULL,
  `estado` CHAR(2) NULL DEFAULT NULL,
  `cep` VARCHAR(12) NULL DEFAULT NULL,
  `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `referencia_local` VARCHAR(255) NULL DEFAULT NULL,
  `ativo` TINYINT NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_clientes_nome` (`nome` ASC) VISIBLE,
  INDEX `idx_clientes_cpf_cnpj` (`cpf_cnpj` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`propriedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`propriedades` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `cliente_id` BIGINT UNSIGNED NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `numero` VARCHAR(20) NULL DEFAULT NULL,
  `complemento` VARCHAR(120) NULL DEFAULT NULL,
  `bairro` VARCHAR(120) NULL DEFAULT NULL,
  `municipio` VARCHAR(120) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `cep` VARCHAR(12) NULL DEFAULT NULL,
  `localizacao_descritiva` TEXT NULL DEFAULT NULL,
  `referencia_local` VARCHAR(255) NULL DEFAULT NULL,
  `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `area_total` DECIMAL(14,2) NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_propriedades_cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `idx_propriedades_nome` (`nome` ASC) VISIBLE,
  INDEX `idx_propriedades_municipio_estado` (`municipio` ASC, `estado` ASC) VISIBLE,
  INDEX `fk_propriedades_cliente_id` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_propriedades_cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `AgroFlightOps`.`clientes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`culturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`culturas` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `ativo` TINYINT NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`nome` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`talhoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`talhoes` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `propriedade_id` BIGINT UNSIGNED NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `area_hectares` DECIMAL(14,2) NOT NULL,
  `cultura_id` BIGINT UNSIGNED NOT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `ponto_referencia` VARCHAR(255) NULL DEFAULT NULL,
  `geojson` JSON NULL DEFAULT NULL,
  `ativo` TINYINT NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_talhoes_propriedade_nome` (`propriedade_id` ASC, `nome` ASC) VISIBLE,
  INDEX `idx_talhoes_propriedade_id` (`propriedade_id` ASC) VISIBLE,
  INDEX `idx_talhoes_cultura_id` (`cultura_id` ASC) VISIBLE,
  INDEX `idx_talhoes_nome` (`nome` ASC) VISIBLE,
  INDEX `fk_talhoes_cultura_id` (`cultura_id` ASC) VISIBLE,
  CONSTRAINT `fk_talhoes_propriedade_id`
    FOREIGN KEY (`propriedade_id`)
    REFERENCES `AgroFlightOps`.`propriedades` (`id`),
  CONSTRAINT `fk_talhoes_cultura_id`
    FOREIGN KEY (`cultura_id`)
    REFERENCES `AgroFlightOps`.`culturas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`drones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`drones` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `identificacao` VARCHAR(120) NOT NULL,
  `modelo` VARCHAR(120) NOT NULL,
  `fabricante` VARCHAR(120) NULL DEFAULT NULL,
  `capacidade_litros` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `horas_voadas` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `ultima_manutencao_em` DATE NULL DEFAULT NULL,
  `ativo` TINYINT NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`identificacao` ASC) VISIBLE,
  INDEX `idx_drones_status` (`status` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`baterias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`baterias` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `identificacao` VARCHAR(120) NOT NULL,
  `drone_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `ciclos` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(30) NOT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `ativo` TINYINT NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`identificacao` ASC) VISIBLE,
  INDEX `idx_baterias_drone_id` (`drone_id` ASC) VISIBLE,
  INDEX `idx_baterias_status` (`status` ASC) VISIBLE,
  INDEX `fk_baterias_drone_id` (`drone_id` ASC) VISIBLE,
  CONSTRAINT `fk_baterias_drone_id`
    FOREIGN KEY (`drone_id`)
    REFERENCES `AgroFlightOps`.`drones` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`insumos` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `fabricante` VARCHAR(120) NULL DEFAULT NULL,
  `unidade_medida` VARCHAR(30) NOT NULL,
  `saldo_atual` DECIMAL(14,3) NOT NULL DEFAULT 0,
  `lote` VARCHAR(100) NULL DEFAULT NULL,
  `validade` DATE NULL DEFAULT NULL,
  `ativo` TINYINT NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_insumos_nome` (`nome` ASC) VISIBLE,
  INDEX `idx_insumos_lote` (`lote` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`tipos_ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`tipos_ocorrencia` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `ativo` TINYINT NOT NULL DEFAULT TRUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`nome` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`itens_checklist_padrao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`itens_checklist_padrao` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nome_item` VARCHAR(200) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `obrigatorio` TINYINT NOT NULL DEFAULT TRUE,
  `ativo` TINYINT NOT NULL DEFAULT TRUE,
  `ordem_exibicao` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_itens_checklist_padrao_nome_item` (`nome_item` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`ordens_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`ordens_servico` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `cliente_id` BIGINT UNSIGNED NOT NULL,
  `propriedade_id` BIGINT UNSIGNED NOT NULL,
  `talhao_id` BIGINT UNSIGNED NOT NULL,
  `cultura_id` BIGINT UNSIGNED NOT NULL,
  `tipo_aplicacao` VARCHAR(120) NOT NULL,
  `prioridade` VARCHAR(30) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `data_prevista` DATE NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `motivo_rejeicao` TEXT NULL DEFAULT NULL,
  `motivo_cancelamento` TEXT NULL DEFAULT NULL,
  `criado_por` BIGINT UNSIGNED NOT NULL,
  `aprovado_por` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`codigo` ASC) VISIBLE,
  INDEX `idx_ordens_servico_cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `idx_ordens_servico_propriedade_id` (`propriedade_id` ASC) VISIBLE,
  INDEX `idx_ordens_servico_talhao_id` (`talhao_id` ASC) VISIBLE,
  INDEX `idx_ordens_servico_cultura_id` (`cultura_id` ASC) VISIBLE,
  INDEX `idx_ordens_servico_status` (`status` ASC) VISIBLE,
  INDEX `idx_ordens_servico_data_prevista` (`data_prevista` ASC) VISIBLE,
  INDEX `idx_ordens_servico_criado_por` (`criado_por` ASC) VISIBLE,
  INDEX `fk_ordens_servico_cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_ordens_servico_propriedade_id` (`propriedade_id` ASC) VISIBLE,
  INDEX `fk_ordens_servico_talhao_id` (`talhao_id` ASC) VISIBLE,
  INDEX `fk_ordens_servico_cultura_id` (`cultura_id` ASC) VISIBLE,
  INDEX `fk_ordens_servico_criado_por` (`criado_por` ASC) VISIBLE,
  INDEX `fk_ordens_servico_aprovado_por` (`aprovado_por` ASC) VISIBLE,
  CONSTRAINT `fk_ordens_servico_cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `AgroFlightOps`.`clientes` (`id`),
  CONSTRAINT `fk_ordens_servico_propriedade_id`
    FOREIGN KEY (`propriedade_id`)
    REFERENCES `AgroFlightOps`.`propriedades` (`id`),
  CONSTRAINT `fk_ordens_servico_talhao_id`
    FOREIGN KEY (`talhao_id`)
    REFERENCES `AgroFlightOps`.`talhoes` (`id`),
  CONSTRAINT `fk_ordens_servico_cultura_id`
    FOREIGN KEY (`cultura_id`)
    REFERENCES `AgroFlightOps`.`culturas` (`id`),
  CONSTRAINT `fk_ordens_servico_criado_por`
    FOREIGN KEY (`criado_por`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`),
  CONSTRAINT `fk_ordens_servico_aprovado_por`
    FOREIGN KEY (`aprovado_por`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`historico_status_os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`historico_status_os` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `ordem_servico_id` BIGINT UNSIGNED NOT NULL,
  `status_anterior` VARCHAR(30) NULL DEFAULT NULL,
  `status_novo` VARCHAR(30) NOT NULL,
  `motivo` TEXT NULL DEFAULT NULL,
  `alterado_por` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_historico_status_os_ordem_servico_id` (`ordem_servico_id` ASC) VISIBLE,
  INDEX `idx_historico_status_os_created_at` (`created_at` ASC) VISIBLE,
  INDEX `fk_historico_status_os_ordem_servico_id` (`ordem_servico_id` ASC) VISIBLE,
  INDEX `fk_historico_status_os_alterado_por` (`alterado_por` ASC) VISIBLE,
  CONSTRAINT `fk_historico_status_os_ordem_servico_id`
    FOREIGN KEY (`ordem_servico_id`)
    REFERENCES `AgroFlightOps`.`ordens_servico` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_historico_status_os_alterado_por`
    FOREIGN KEY (`alterado_por`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`missoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`missoes` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NOT NULL,
  `ordem_servico_id` BIGINT UNSIGNED NOT NULL,
  `piloto_id` BIGINT UNSIGNED NOT NULL,
  `tecnico_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `drone_id` BIGINT UNSIGNED NOT NULL,
  `data_agendada` DATE NOT NULL,
  `hora_agendada` TIME NOT NULL,
  `area_prevista` DECIMAL(14,2) NOT NULL,
  `area_realizada` DECIMAL(14,2) NULL DEFAULT NULL,
  `volume_previsto` DECIMAL(14,3) NOT NULL,
  `volume_realizado` DECIMAL(14,3) NULL DEFAULT NULL,
  `janela_operacional` VARCHAR(255) NULL DEFAULT NULL,
  `restricoes` TEXT NULL DEFAULT NULL,
  `observacoes_planejamento` TEXT NULL DEFAULT NULL,
  `observacoes_execucao` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(40) NOT NULL,
  `latitude_operacao` DECIMAL(10,7) NULL DEFAULT NULL,
  `longitude_operacao` DECIMAL(10,7) NULL DEFAULT NULL,
  `endereco_operacao` VARCHAR(255) NULL DEFAULT NULL,
  `referencia_operacao` VARCHAR(255) NULL DEFAULT NULL,
  `iniciado_em` TIMESTAMP NOT NULL,
  `finalizado_em` TIMESTAMP NOT NULL,
  `encerrado_tecnicamente_em` TIMESTAMP NOT NULL,
  `encerrado_financeiramente_em` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`codigo` ASC) VISIBLE,
  INDEX `idx_missoes_ordem_servico_id` (`ordem_servico_id` ASC) VISIBLE,
  INDEX `idx_missoes_piloto_id` (`piloto_id` ASC) VISIBLE,
  INDEX `idx_missoes_tecnico_id` (`tecnico_id` ASC) VISIBLE,
  INDEX `idx_missoes_drone_id` (`drone_id` ASC) VISIBLE,
  INDEX `idx_missoes_status` (`status` ASC) VISIBLE,
  INDEX `idx_missoes_data_agendada` (`data_agendada` ASC) VISIBLE,
  INDEX `idx_missoes_data_hora` (`data_agendada` ASC, `hora_agendada` ASC) VISIBLE,
  INDEX `fk_missoes_ordem_servico_id` (`ordem_servico_id` ASC) VISIBLE,
  INDEX `fk_missoes_piloto_id` (`piloto_id` ASC) VISIBLE,
  INDEX `fk_missoes_drone_id` (`drone_id` ASC) VISIBLE,
  INDEX `fk_missoes_tecnico_id` (`tecnico_id` ASC) VISIBLE,
  CONSTRAINT `fk_missoes_ordem_servico_id`
    FOREIGN KEY (`ordem_servico_id`)
    REFERENCES `AgroFlightOps`.`ordens_servico` (`id`),
  CONSTRAINT `fk_missoes_piloto_id`
    FOREIGN KEY (`piloto_id`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`),
  CONSTRAINT `fk_missoes_drone_id`
    FOREIGN KEY (`drone_id`)
    REFERENCES `AgroFlightOps`.`drones` (`id`),
  CONSTRAINT `fk_missoes_tecnico_id`
    FOREIGN KEY (`tecnico_id`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`historico_status_missao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`historico_status_missao` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `missao_id` BIGINT UNSIGNED NOT NULL,
  `status_anterior` VARCHAR(40) NULL DEFAULT NULL,
  `status_novo` VARCHAR(40) NOT NULL,
  `motivo` TEXT NULL DEFAULT NULL,
  `alterado_por` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_historico_status_missao_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `idx_historico_status_missao_created_at` (`created_at` ASC) VISIBLE,
  INDEX `fk_historico_status_missao_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `fk_historico_status_missao_alterado_por` (`alterado_por` ASC) VISIBLE,
  CONSTRAINT `fk_historico_status_missao_missao_id`
    FOREIGN KEY (`missao_id`)
    REFERENCES `AgroFlightOps`.`missoes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_historico_status_missao_alterado_por`
    FOREIGN KEY (`alterado_por`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`missao_baterias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`missao_baterias` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `missao_id` BIGINT UNSIGNED NOT NULL,
  `bateria_id` BIGINT UNSIGNED NOT NULL,
  `ordem_uso` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_missao_baterias` (`missao_id` ASC, `bateria_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_missao_baterias_ordem` (`missao_id` ASC, `ordem_uso` ASC) VISIBLE,
  INDEX `idx_missao_baterias_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `idx_missao_baterias_bateria_id` (`bateria_id` ASC) VISIBLE,
  INDEX `fk_missao_baterias_bateria_id` (`bateria_id` ASC) VISIBLE,
  CONSTRAINT `fk_missao_baterias_missao_id`
    FOREIGN KEY (`missao_id`)
    REFERENCES `AgroFlightOps`.`missoes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_missao_baterias_bateria_id`
    FOREIGN KEY (`bateria_id`)
    REFERENCES `AgroFlightOps`.`baterias` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`reservas_insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`reservas_insumo` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `missao_id` BIGINT UNSIGNED NOT NULL,
  `insumo_id` BIGINT UNSIGNED NOT NULL,
  `quantidade_prevista` DECIMAL(14,3) NOT NULL,
  `unidade_medida` VARCHAR(30) NOT NULL,
  `justificativa_excesso` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_reservas_insumo_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `idx_reservas_insumo_insumo_id` (`insumo_id` ASC) VISIBLE,
  INDEX `fk_reservas_insumo_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `fk_reservas_insumo_insumo_id` (`insumo_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_insumo_missao_id`
    FOREIGN KEY (`missao_id`)
    REFERENCES `AgroFlightOps`.`missoes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_reservas_insumo_insumo_id`
    FOREIGN KEY (`insumo_id`)
    REFERENCES `AgroFlightOps`.`insumos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`consumos_insumo_missao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`consumos_insumo_missao` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `missao_id` BIGINT UNSIGNED NOT NULL,
  `insumo_id` BIGINT UNSIGNED NOT NULL,
  `quantidade_realizada` DECIMAL(14,3) NOT NULL,
  `unidade_medida` VARCHAR(30) NOT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `justificativa_excesso` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_consumos_insumo_missao_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `idx_consumos_insumo_missao_insumo_id` (`insumo_id` ASC) VISIBLE,
  INDEX `fk_consumos_insumo_missao_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `fk_consumos_insumo_missao_insumo_id` (`insumo_id` ASC) VISIBLE,
  CONSTRAINT `fk_consumos_insumo_missao_missao_id`
    FOREIGN KEY (`missao_id`)
    REFERENCES `AgroFlightOps`.`missoes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_consumos_insumo_missao_insumo_id`
    FOREIGN KEY (`insumo_id`)
    REFERENCES `AgroFlightOps`.`insumos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`checklists_missao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`checklists_missao` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `missao_id` BIGINT UNSIGNED NOT NULL,
  `status_geral` VARCHAR(30) NOT NULL,
  `preenchido_por` BIGINT UNSIGNED NOT NULL,
  `revisado_por` BIGINT UNSIGNED NULL DEFAULT NULL,
  `preenchido_em` TIMESTAMP NOT NULL,
  `revisado_em` TIMESTAMP NOT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`missao_id` ASC) VISIBLE,
  INDEX `idx_checklists_missao_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `fk_checklists_missao_preenchido_por` (`preenchido_por` ASC) VISIBLE,
  INDEX `fk_checklists_missao_revisado_por` (`revisado_por` ASC) VISIBLE,
  CONSTRAINT `fk_checklists_missao_missao_id`
    FOREIGN KEY (`missao_id`)
    REFERENCES `AgroFlightOps`.`missoes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_checklists_missao_preenchido_por`
    FOREIGN KEY (`preenchido_por`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`),
  CONSTRAINT `fk_checklists_missao_revisado_por`
    FOREIGN KEY (`revisado_por`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`itens_checklist_missao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`itens_checklist_missao` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `checklist_id` BIGINT UNSIGNED NOT NULL,
  `nome_item` VARCHAR(200) NOT NULL,
  `obrigatorio` TINYINT NOT NULL DEFAULT TRUE,
  `status_item` VARCHAR(20) NOT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_itens_checklist_missao_checklist_id` (`checklist_id` ASC) VISIBLE,
  INDEX `fk_itens_checklist_missao_checklist_id` (`checklist_id` ASC) VISIBLE,
  CONSTRAINT `fk_itens_checklist_missao_checklist_id`
    FOREIGN KEY (`checklist_id`)
    REFERENCES `AgroFlightOps`.`checklists_missao` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`ocorrencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`ocorrencias` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `missao_id` BIGINT UNSIGNED NOT NULL,
  `tipo_ocorrencia_id` BIGINT UNSIGNED NOT NULL,
  `descricao` TEXT NOT NULL,
  `severidade` VARCHAR(20) NOT NULL,
  `registrada_por` BIGINT UNSIGNED NOT NULL,
  `registrada_em` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_ocorrencias_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `idx_ocorrencias_tipo_ocorrencia_id` (`tipo_ocorrencia_id` ASC) VISIBLE,
  INDEX `idx_ocorrencias_registrada_em` (`registrada_em` ASC) VISIBLE,
  INDEX `fk_ocorrencias_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `fk_ocorrencias_tipo_ocorrencia_id` (`tipo_ocorrencia_id` ASC) VISIBLE,
  INDEX `fk_ocorrencias_registrada_por` (`registrada_por` ASC) VISIBLE,
  CONSTRAINT `fk_ocorrencias_missao_id`
    FOREIGN KEY (`missao_id`)
    REFERENCES `AgroFlightOps`.`missoes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_ocorrencias_tipo_ocorrencia_id`
    FOREIGN KEY (`tipo_ocorrencia_id`)
    REFERENCES `AgroFlightOps`.`tipos_ocorrencia` (`id`),
  CONSTRAINT `fk_ocorrencias_registrada_por`
    FOREIGN KEY (`registrada_por`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`evidencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`evidencias` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `missao_id` BIGINT UNSIGNED NOT NULL,
  `nome_arquivo` VARCHAR(255) NOT NULL,
  `url_arquivo` TEXT NULL DEFAULT NULL,
  `tipo_arquivo` VARCHAR(80) NULL DEFAULT NULL,
  `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `enviado_por` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_evidencias_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `idx_evidencias_enviado_por` (`enviado_por` ASC) VISIBLE,
  INDEX `fk_evidencias_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `fk_evidencias_enviado_por` (`enviado_por` ASC) VISIBLE,
  CONSTRAINT `fk_evidencias_missao_id`
    FOREIGN KEY (`missao_id`)
    REFERENCES `AgroFlightOps`.`missoes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_evidencias_enviado_por`
    FOREIGN KEY (`enviado_por`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`manutencoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`manutencoes` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `drone_id` BIGINT UNSIGNED NOT NULL,
  `tipo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `data_manutencao` DATE NOT NULL,
  `proxima_manutencao` DATE NULL DEFAULT NULL,
  `horas_na_data` DECIMAL(12,2) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_manutencoes_drone_id` (`drone_id` ASC) VISIBLE,
  INDEX `idx_manutencoes_data_manutencao` (`data_manutencao` ASC) VISIBLE,
  INDEX `fk_manutencoes_drone_id` (`drone_id` ASC) VISIBLE,
  CONSTRAINT `fk_manutencoes_drone_id`
    FOREIGN KEY (`drone_id`)
    REFERENCES `AgroFlightOps`.`drones` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`financeiro_missao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`financeiro_missao` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `missao_id` BIGINT UNSIGNED NOT NULL,
  `custo_estimado` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `custo_realizado` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `valor_faturado` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `status_financeiro` VARCHAR(30) NOT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `fechado_por` BIGINT UNSIGNED NULL DEFAULT NULL,
  `fechado_em` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`missao_id` ASC) VISIBLE,
  INDEX `idx_financeiro_missao_missao_id` (`missao_id` ASC) VISIBLE,
  INDEX `idx_financeiro_missao_status_financeiro` (`status_financeiro` ASC) VISIBLE,
  INDEX `fk_financeiro_missao_fechado_por` (`fechado_por` ASC) VISIBLE,
  CONSTRAINT `fk_financeiro_missao_missao_id`
    FOREIGN KEY (`missao_id`)
    REFERENCES `AgroFlightOps`.`missoes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_financeiro_missao_fechado_por`
    FOREIGN KEY (`fechado_por`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`auditoria` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `entidade` VARCHAR(120) NOT NULL,
  `entidade_id` BIGINT UNSIGNED NOT NULL,
  `acao` VARCHAR(120) NOT NULL,
  `valor_anterior` JSON NULL DEFAULT NULL,
  `valor_novo` JSON NULL DEFAULT NULL,
  `usuario_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_auditoria_entidade_entidade_id` (`entidade` ASC, `entidade_id` ASC) VISIBLE,
  INDEX `idx_auditoria_usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_auditoria_created_at` (`created_at` ASC) VISIBLE,
  INDEX `fk_auditoria_usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_auditoria_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `AgroFlightOps`.`documentos_oficiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgroFlightOps`.`documentos_oficiais` (
  `id` BIGINT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `entidade` VARCHAR(80) NOT NULL,
  `entidade_id` BIGINT UNSIGNED NOT NULL,
  `tipo_documento` VARCHAR(120) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `nome_arquivo` VARCHAR(255) NOT NULL,
  `content_type` VARCHAR(120) NOT NULL,
  `s3_key` TEXT NOT NULL,
  `bucket_s3` VARCHAR(255) NULL DEFAULT NULL,
  `data_emissao` DATE NULL DEFAULT NULL,
  `data_validade` DATE NULL DEFAULT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'ATIVO',
  `enviado_por` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_documentos_oficiais_entidade_entidade_id` (`entidade` ASC, `entidade_id` ASC) VISIBLE,
  INDEX `idx_documentos_oficiais_tipo_documento` (`tipo_documento` ASC) VISIBLE,
  INDEX `idx_documentos_oficiais_status` (`status` ASC) VISIBLE,
  INDEX `idx_documentos_oficiais_data_validade` (`data_validade` ASC) VISIBLE,
  INDEX `fk_documentos_oficiais_enviado_por` (`enviado_por` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_oficiais_enviado_por`
    FOREIGN KEY (`enviado_por`)
    REFERENCES `AgroFlightOps`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
